export const PRODUCTS = [
  {
    id: "w1",
    name: "Château Demo Cabernet Sauvignon 2021",
    category: "wine",
    type: "Red",
    grape: "Cabernet Sauvignon",
    region: "Napa Valley",
    country: "USA",
    vintage: 2021,
    abv: 14.5,
    volume_ml: 750,
    price_cents: 3499,
    rating: 4.6,
    badges: ["Staff Pick"],
    inventory: 24,
    flavor_notes: ["blackcurrant", "cedar", "dark chocolate"],
    pairings: ["ribeye", "mushroom risotto"],
    image_url: "https://picsum.photos/seed/wine1/800/1066"
  },
  {
    id: "w2",
    name: "Willow Lane Pinot Noir 2020",
    category: "wine",
    type: "Red",
    grape: "Pinot Noir",
    region: "Willamette Valley",
    country: "USA",
    vintage: 2020,
    abv: 13.5,
    volume_ml: 750,
    price_cents: 2699,
    rating: 4.4,
    badges: [],
    inventory: 18,
    flavor_notes: ["cherry", "raspberry", "spice"],
    pairings: ["salmon", "duck"],
    image_url: "https://picsum.photos/seed/wine2/800/1066"
  },
  {
    id: "w3",
    name: "Coastal Breeze Chardonnay 2022",
    category: "wine",
    type: "White",
    grape: "Chardonnay",
    region: "Sonoma",
    country: "USA",
    vintage: 2022,
    abv: 13.0,
    volume_ml: 750,
    price_cents: 1899,
    rating: 4.2,
    badges: ["Best Value"],
    inventory: 42,
    flavor_notes: ["apple", "vanilla", "butter"],
    pairings: ["roast chicken", "lobster"],
    image_url: "https://picsum.photos/seed/wine3/800/1066"
  },
  {
    id: "w4",
    name: "Côte de Demo Rosé 2023",
    category: "wine",
    type: "Rosé",
    grape: "Grenache",
    region: "Provence",
    country: "France",
    vintage: 2023,
    abv: 12.5,
    volume_ml: 750,
    price_cents: 1599,
    rating: 4.3,
    badges: [],
    inventory: 35,
    flavor_notes: ["strawberry", "melon", "rose"],
    pairings: ["salads", "tapas"],
    image_url: "https://picsum.photos/seed/wine4/800/1066"
  },
  {
    id: "w5",
    name: "Alpine Spark Brut NV",
    category: "wine",
    type: "Sparkling",
    grape: "Chardonnay",
    region: "Trentino",
    country: "Italy",
    vintage: null,
    abv: 12.0,
    volume_ml: 750,
    price_cents: 2199,
    rating: 4.1,
    badges: [],
    inventory: 28,
    flavor_notes: ["green apple", "brioche"],
    pairings: ["oysters", "chips"],
    image_url: "https://picsum.photos/seed/wine5/800/1066"
  },
  {
    id: "w6",
    name: "Late Harvest Gold Riesling 2019",
    category: "wine",
    type: "Dessert",
    grape: "Riesling",
    region: "Mosel",
    country: "Germany",
    vintage: 2019,
    abv: 9.0,
    volume_ml: 375,
    price_cents: 1799,
    rating: 4.5,
    badges: ["Staff Pick"],
    inventory: 9,
    flavor_notes: ["apricot", "honey", "peach"],
    pairings: ["cheesecake", "blue cheese"],
    image_url: "https://picsum.photos/seed/wine6/800/1066"
  },
  {
    id: "w7",
    name: "Andes Crest Malbec 2021",
    category: "wine",
    type: "Red",
    grape: "Malbec",
    region: "Mendoza",
    country: "Argentina",
    vintage: 2021,
    abv: 14.0,
    volume_ml: 750,
    price_cents: 1499,
    rating: 4.0,
    badges: [],
    inventory: 31,
    flavor_notes: ["plum", "violet", "cocoa"],
    pairings: ["grilled meats"],
    image_url: "https://picsum.photos/seed/wine7/800/1066"
  },
  {
    id: "w8",
    name: "Loire Valley Sancerre 2022",
    category: "wine",
    type: "White",
    grape: "Sauvignon Blanc",
    region: "Loire",
    country: "France",
    vintage: 2022,
    abv: 12.5,
    volume_ml: 750,
    price_cents: 2799,
    rating: 4.6,
    badges: ["Staff Pick"],
    inventory: 12,
    flavor_notes: ["citrus", "flint", "herb"],
    pairings: ["goat cheese", "asparagus"],
    image_url: "https://picsum.photos/seed/wine8/800/1066"
  },
  {
    id: "w9",
    name: "Rioja Reserva 2018",
    category: "wine",
    type: "Red",
    grape: "Tempranillo",
    region: "Rioja",
    country: "Spain",
    vintage: 2018,
    abv: 14.0,
    volume_ml: 750,
    price_cents: 2399,
    rating: 4.4,
    badges: [],
    inventory: 22,
    flavor_notes: ["red fruit", "vanilla", "leather"],
    pairings: ["paella", "pork"],
    image_url: "https://picsum.photos/seed/wine9/800/1066"
  },
  {
    id: "w10",
    name: "Bourgogne Blanc 2021",
    category: "wine",
    type: "White",
    grape: "Chardonnay",
    region: "Burgundy",
    country: "France",
    vintage: 2021,
    abv: 13.0,
    volume_ml: 750,
    price_cents: 3299,
    rating: 4.7,
    badges: ["Staff Pick"],
    inventory: 7,
    flavor_notes: ["pear", "hazelnut", "mineral"],
    pairings: ["seafood", "poultry"],
    image_url: "https://picsum.photos/seed/wine10/800/1066"
  },
  {
    id: "w11",
    name: "Chianti Classico 2019",
    category: "wine",
    type: "Red",
    grape: "Sangiovese",
    region: "Tuscany",
    country: "Italy",
    vintage: 2019,
    abv: 13.5,
    volume_ml: 750,
    price_cents: 1999,
    rating: 4.2,
    badges: [],
    inventory: 16,
    flavor_notes: ["cherry", "earth", "cedar"],
    pairings: ["pasta", "pizza"],
    image_url: "https://picsum.photos/seed/wine11/800/1066"
  },
  {
    id: "w12",
    name: "Marlborough Sauvignon Blanc 2023",
    category: "wine",
    type: "White",
    grape: "Sauvignon Blanc",
    region: "Marlborough",
    country: "New Zealand",
    vintage: 2023,
    abv: 12.5,
    volume_ml: 750,
    price_cents: 1599,
    rating: 4.1,
    badges: ["Best Value"],
    inventory: 40,
    flavor_notes: ["lime", "passionfruit"],
    pairings: ["salads", "seafood"],
    image_url: "https://picsum.photos/seed/wine12/800/1066"
  },

  /* Spirits */
  {
    id: "s1",
    name: "High Ridge Bourbon",
    category: "spirits",
    type: "Bourbon",
    grape: null,
    region: "Kentucky",
    country: "USA",
    vintage: null,
    abv: 45.0,
    volume_ml: 750,
    price_cents: 2999,
    rating: 4.3,
    badges: [],
    inventory: 20,
    flavor_notes: ["caramel", "oak", "vanilla"],
    pairings: ["bbq"] ,
    image_url: "https://picsum.photos/seed/bourbon1/800/1066"
  },
  {
    id: "s2",
    name: "Clear Spring Gin",
    category: "spirits",
    type: "Gin",
    grape: null,
    region: "London",
    country: "UK",
    vintage: null,
    abv: 41.5,
    volume_ml: 750,
    price_cents: 2499,
    rating: 4.2,
    badges: [],
    inventory: 26,
    flavor_notes: ["juniper", "citrus"],
    pairings: ["tonic", "cured salmon"],
    image_url: "https://picsum.photos/seed/gin1/800/1066"
  },
  {
    id: "s3",
    name: "Agave Azul Tequila Blanco",
    category: "spirits",
    type: "Tequila",
    grape: null,
    region: "Jalisco",
    country: "Mexico",
    vintage: null,
    abv: 40.0,
    volume_ml: 750,
    price_cents: 3299,
    rating: 4.5,
    badges: ["Staff Pick"],
    inventory: 14,
    flavor_notes: ["agave", "pepper", "citrus"],
    pairings: ["ceviche", "tacos"],
    image_url: "https://picsum.photos/seed/tequila1/800/1066"
  },

  /* Liquor */
  {
    id: "l1",
    name: "Classic Dry Vermouth",
    category: "liquor",
    type: "Vermouth",
    grape: null,
    region: "Piedmont",
    country: "Italy",
    vintage: null,
    abv: 18.0,
    volume_ml: 750,
    price_cents: 999,
    rating: 4.0,
    badges: [],
    inventory: 30,
    flavor_notes: ["herbal", "bitter"],
    pairings: ["martinis"],
    image_url: "https://picsum.photos/seed/vermouth/800/1066"
  },
  {
    id: "l2",
    name: "Orange Liqueur",
    category: "liquor",
    type: "Liqueur",
    grape: null,
    region: "Cognac",
    country: "France",
    vintage: null,
    abv: 40.0,
    volume_ml: 750,
    price_cents: 2199,
    rating: 4.1,
    badges: [],
    inventory: 19,
    flavor_notes: ["orange", "vanilla"],
    pairings: ["margaritas", "sidecars"],
    image_url: "https://picsum.photos/seed/orangelik/800/1066"
  },

  /* More wines for grid */
  {
    id: "w13",
    name: "Rhone Valley GSM 2020",
    category: "wine",
    type: "Red",
    grape: "Grenache Blend",
    region: "Rhône",
    country: "France",
    vintage: 2020,
    abv: 14.0,
    volume_ml: 750,
    price_cents: 2199,
    rating: 4.3,
    badges: [],
    inventory: 21,
    flavor_notes: ["berry", "garrigue"],
    pairings: ["lamb", "stew"],
    image_url: "https://picsum.photos/seed/wine13/800/1066"
  },
  {
    id: "w14",
    name: "Barossa Shiraz 2019",
    category: "wine",
    type: "Red",
    grape: "Shiraz",
    region: "Barossa",
    country: "Australia",
    vintage: 2019,
    abv: 14.5,
    volume_ml: 750,
    price_cents: 2599,
    rating: 4.5,
    badges: [],
    inventory: 13,
    flavor_notes: ["blackberry", "pepper"],
    pairings: ["bbq", "stews"],
    image_url: "https://picsum.photos/seed/wine14/800/1066"
  },
  {
    id: "w15",
    name: "Albariño Rías Baixas 2022",
    category: "wine",
    type: "White",
    grape: "Albariño",
    region: "Rías Baixas",
    country: "Spain",
    vintage: 2022,
    abv: 12.5,
    volume_ml: 750,
    price_cents: 1899,
    rating: 4.2,
    badges: [],
    inventory: 23,
    flavor_notes: ["citrus", "saline"],
    pairings: ["seafood"],
    image_url: "https://picsum.photos/seed/wine15/800/1066"
  },
  {
    id: "w16",
    name: "Rosso di Demo 2020",
    category: "wine",
    type: "Red",
    grape: "Nebbiolo",
    region: "Piedmont",
    country: "Italy",
    vintage: 2020,
    abv: 13.5,
    volume_ml: 750,
    price_cents: 2899,
    rating: 4.4,
    badges: ["Staff Pick"],
    inventory: 11,
    flavor_notes: ["rose", "tar", "cherry"],
    pairings: ["truffles", "beef"],
    image_url: "https://picsum.photos/seed/wine16/800/1066"
  },
  {
    id: "w17",
    name: "Cava Brut Rosé NV",
    category: "wine",
    type: "Sparkling",
    grape: "Trepat",
    region: "Catalonia",
    country: "Spain",
    vintage: null,
    abv: 11.5,
    volume_ml: 750,
    price_cents: 1299,
    rating: 4.0,
    badges: ["Best Value"],
    inventory: 33,
    flavor_notes: ["strawberry", "citrus"],
    pairings: ["tapas"],
    image_url: "https://picsum.photos/seed/wine17/800/1066"
  },
  {
    id: "w18",
    name: "German Riesling Kabinett 2021",
    category: "wine",
    type: "White",
    grape: "Riesling",
    region: "Mosel",
    country: "Germany",
    vintage: 2021,
    abv: 10.5,
    volume_ml: 750,
    price_cents: 1699,
    rating: 4.1,
    badges: [],
    inventory: 29,
    flavor_notes: ["green apple", "slate"],
    pairings: ["spicy food"] ,
    image_url: "https://picsum.photos/seed/wine18/800/1066"
  },
  {
    id: "w19",
    name: "Portuguese Vinho Verde 2023",
    category: "wine",
    type: "White",
    grape: "Loureiro",
    region: "Minho",
    country: "Portugal",
    vintage: 2023,
    abv: 11.0,
    volume_ml: 750,
    price_cents: 1099,
    rating: 4.0,
    badges: [],
    inventory: 45,
    flavor_notes: ["citrus", "effervescence"],
    pairings: ["shellfish"],
    image_url: "https://picsum.photos/seed/wine19/800/1066"
  },
  {
    id: "w20",
    name: "Rosé of Pinot Noir 2023",
    category: "wine",
    type: "Rosé",
    grape: "Pinot Noir",
    region: "Sonoma",
    country: "USA",
    vintage: 2023,
    abv: 12.5,
    volume_ml: 750,
    price_cents: 1799,
    rating: 4.2,
    badges: [],
    inventory: 27,
    flavor_notes: ["watermelon", "strawberry"],
    pairings: ["salads", "pasta"],
    image_url: "https://picsum.photos/seed/wine20/800/1066"
  },
  {
    id: "w21",
    name: "Nero d'Avola 2020",
    category: "wine",
    type: "Red",
    grape: "Nero d'Avola",
    region: "Sicily",
    country: "Italy",
    vintage: 2020,
    abv: 13.5,
    volume_ml: 750,
    price_cents: 1499,
    rating: 4.0,
    badges: [],
    inventory: 17,
    flavor_notes: ["plum", "spice"],
    pairings: ["pizza", "eggplant"],
    image_url: "https://picsum.photos/seed/wine21/800/1066"
  },
  {
    id: "w22",
    name: "Beaujolais Villages 2022",
    category: "wine",
    type: "Red",
    grape: "Gamay",
    region: "Beaujolais",
    country: "France",
    vintage: 2022,
    abv: 12.5,
    volume_ml: 750,
    price_cents: 1699,
    rating: 4.1,
    badges: [],
    inventory: 25,
    flavor_notes: ["raspberry", "violet"],
    pairings: ["charcuterie"],
    image_url: "https://picsum.photos/seed/wine22/800/1066"
  },
  {
    id: "w23",
    name: "South African Chenin Blanc 2021",
    category: "wine",
    type: "White",
    grape: "Chenin Blanc",
    region: "Stellenbosch",
    country: "South Africa",
    vintage: 2021,
    abv: 13.0,
    volume_ml: 750,
    price_cents: 1599,
    rating: 4.0,
    badges: [],
    inventory: 36,
    flavor_notes: ["pear", "quince"],
    pairings: ["pork", "seafood"],
    image_url: "https://picsum.photos/seed/wine23/800/1066"
  },
  {
    id: "w24",
    name: "Demo Cabernet Reserve 2018",
    category: "wine",
    type: "Red",
    grape: "Cabernet Sauvignon",
    region: "Napa Valley",
    country: "USA",
    vintage: 2018,
    abv: 14.5,
    volume_ml: 750,
    price_cents: 5499,
    rating: 4.8,
    badges: ["Staff Pick"],
    inventory: 5,
    flavor_notes: ["blackberry", "graphite", "cocoa"],
    pairings: ["steak", "hard cheese"],
    image_url: "https://picsum.photos/seed/wine24/800/1066"
  }
];

export const FEATURED_IDS = ["w1","w2","w3","w4","w5","w6","w7","w8","w9","w10","w11","w12"];


